services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "127.0.0.1:81:80"
        volumes:
            - ./:/var/www/html
            - ./docker/configs/nginx:/etc/nginx/conf.d
            - ./docker/logs/nginx:/var/log/nginx
        depends_on:
            - php-fpm
        networks:
            - laravel

    php-fpm:
        build:
            context: ./docker
        container_name: php-fpm
        volumes:
            - ./:/var/www/html
            - ./docker/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - db
        networks:
            - laravel

    db:
        image: postgres:14.7-alpine
        container_name: db-postgres
        hostname: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: laravel
            POSTGRES_DB: laravel
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    db_data:
        driver: local
